import { describe, it, expect } from "vitest";
import {
  hashPassword,
  verifyPassword,
  needsRehash,
  validatePasswordStrength,
  DEFAULT_ITERATIONS,
  MIN_PASSWORD_LENGTH,
} from "./password";

describe("hashPassword", () => {
  it("produces a self-describing hash", async () => {
    const hash = await hashPassword("correct horse battery staple");
    const [algorithm, digest, iterations] = hash.split("$");
    expect(algorithm).toBe("pbkdf2");
    expect(digest).toBe("sha256");
    expect(Number(iterations)).toBe(DEFAULT_ITERATIONS);
  });

  it("salts, so the same password never yields the same hash", async () => {
    const a = await hashPassword("same password", 1000);
    const b = await hashPassword("same password", 1000);
    expect(a).not.toBe(b);
  });
});

describe("verifyPassword", () => {
  it("accepts the right password", async () => {
    const hash = await hashPassword("s3cret-passphrase", 1000);
    expect(await verifyPassword("s3cret-passphrase", hash)).toBe(true);
  });

  it("rejects the wrong password", async () => {
    const hash = await hashPassword("s3cret-passphrase", 1000);
    expect(await verifyPassword("s3cret-passphras", hash)).toBe(false);
  });

  it("is case-sensitive", async () => {
    const hash = await hashPassword("CaseSensitive", 1000);
    expect(await verifyPassword("casesensitive", hash)).toBe(false);
  });

  it("verifies a hash made with a different iteration count", async () => {
    // The count lives in the hash, so old rows keep working after a raise.
    const hash = await hashPassword("portable", 2000);
    expect(await verifyPassword("portable", hash)).toBe(true);
  });

  it("returns false — never throws — for a malformed hash", async () => {
    for (const bad of [
      "",
      "not-a-hash",
      "pbkdf2$sha256$1000$onlyfour",
      "pbkdf2$sha256$abc$c2FsdA==$aGFzaA==",
      "pbkdf2$sha256$0$c2FsdA==$aGFzaA==",
      "bcrypt$sha256$1000$c2FsdA==$aGFzaA==",
      "pbkdf2$sha512$1000$c2FsdA==$aGFzaA==",
      "pbkdf2$sha256$1000$!!!not-base64!!!$aGFzaA==",
    ]) {
      expect(await verifyPassword("anything", bad), bad).toBe(false);
    }
  });

  it("rejects an empty password against a real hash", async () => {
    const hash = await hashPassword("nonempty", 1000);
    expect(await verifyPassword("", hash)).toBe(false);
  });
});

describe("needsRehash", () => {
  it("flags a weaker stored hash", async () => {
    const hash = await hashPassword("old", 1000);
    expect(needsRehash(hash, 2000)).toBe(true);
  });

  it("leaves a current hash alone", async () => {
    const hash = await hashPassword("current", 2000);
    expect(needsRehash(hash, 2000)).toBe(false);
  });

  it("treats an unparseable hash as needing a rehash", () => {
    expect(needsRehash("garbage")).toBe(true);
  });
});

describe("validatePasswordStrength", () => {
  it("rejects anything under the minimum", () => {
    expect(validatePasswordStrength("a".repeat(MIN_PASSWORD_LENGTH - 1))).toBe(
      "tooShort",
    );
  });

  it("accepts the minimum", () => {
    expect(validatePasswordStrength("a".repeat(MIN_PASSWORD_LENGTH))).toBeNull();
  });

  it("rejects whitespace padding used to reach the minimum", () => {
    expect(validatePasswordStrength(`  short  ${" ".repeat(20)}`)).toBe("tooShort");
  });
});

describe("cost at the real iteration count", () => {
  it("hashes and verifies within a sane share of the isolate CPU budget", async () => {
    // Honest measurement, not an assumption: this asserts the production
    // parameters are actually usable on workerd. If a future raise makes login
    // slow, this is what notices.
    const started = Date.now();
    const hash = await hashPassword("realistic-password", DEFAULT_ITERATIONS);
    const verified = await verifyPassword("realistic-password", hash);
    const elapsed = Date.now() - started;

    expect(verified).toBe(true);
    // Two full derivations (hash + verify). Generous ceiling so the test is not
    // flaky on a cold CI runner, but tight enough to catch a 10x regression.
    expect(elapsed, `two PBKDF2 derivations took ${elapsed}ms`).toBeLessThan(10_000);
  });
});

describe("cross-runtime compatibility with the seed script", () => {
  it("verifies a hash produced by Node's webcrypto in workerd", async () => {
    // scripts/seed-admin.mjs hashes in NODE; this code verifies in WORKERD. If
    // the two ever disagree on encoding or parameters, the seeded account
    // silently cannot log in — and nothing else would catch it. Fixture below
    // was generated by that script's algorithm for the password "admin123"
    // (iterations lowered to 1000 to keep the test fast).
    const fromNode =
      "pbkdf2$sha256$1000$cjb9TzNfySOlPpG9wGkIiA==$2XvPuiS4N5p8Hpq4regDlz5kj4kIPltDm9nfmKmmrM0=";

    expect(await verifyPassword("admin123", fromNode)).toBe(true);
    expect(await verifyPassword("admin124", fromNode)).toBe(false);
  });
});
